<<<<<<< HEAD
project_id = "tqifeswxbdjvkrvduhxh"

[functions.sitemap]
verify_jwt = false

[functions.import-rss]
verify_jwt = false

[functions.batch-optimize-images]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false
=======
project_id = "tqifeswxbdjvkrvduhxh"
>>>>>>> 14931d0e8b12acb8851d060f4b486b51b40670df
